import gym
import os
from os import mkdir, path

import re
import numpy as np
LAYOUT = "env"

pattern = re.compile(r'(?<!^)(?=[A-Z])')

for env_spec in gym.envs.registry.all():
    if env_spec.id == "CartPole-v1":
        env = gym.make(env_spec.id)
        # print(type(en))
        docstring = env.unwrapped.__doc__
        print(docstring)
        split = str(type(env.unwrapped)).split(".")

        env_name = split[3]
        env_type = split[2]
        if env_name == "environment":
            env_name = env_spec.id.split("-")[0][4:] 
            camel_env_name = env_name
            env_name = pattern.sub('_', env_name).lower()
        else:
            camel_env_name = env_spec.id.split("-")[0]
        # path for saving video
        v_path = os.path.join("..", "pages", "environments", env_type, env_name + ".mmd")

        front_matter = "---\n"

        front_matter+= "AUTOGENERATED: DO NOT EDIT FILE DIRECTLY\n"

        front_matter+= "layout: env\n"

        front_matter+= f"title: {env_name}\n"

        front_matter+= "grid:\n"

        front_matter+= f"   - Action Space: {env.action_space}\n"

        front_matter+= f"   - Observation Shape: {env.observation_space.shape}\n"

        front_matter+= f"   - Observation High: {np.round(env.observation_space.high, 2)}\n"

        front_matter+= f"   - Observation Low: {np.round(env.observation_space.low, 2)}\n"

        front_matter+= f"   - Import: gym.make(\"{env_spec.id}\")\n"
        # from gym.envs.box2d.bipedal_walker import BipedalWalker

        print(front_matter)
        front_matter += "---\n"


        all_text = front_matter + docstring

        file = open(v_path, "w")
        file.write(all_text)
        file.close()
        

        